data:
  train_de: "data/raw/train.de"
  train_en: "data/raw/train.en"
  val_de: "data/raw/val.de"
  val_en: "data/raw/val.en"
  test_de: "data/raw/test.de"
  test_en: "data/raw/test.en"
  processed_dir: "data/processed"
  max_length: 50
  min_freq: 2

model:
  encoder:
    embedding_dim: 256
    hidden_dim: 512
    num_layers: 2
    dropout: 0.3
    bidirectional: true
  
  decoder:
    embedding_dim: 256
    hidden_dim: 512
    num_layers: 2
    dropout: 0.3
    attention_dim: 512

training:
  batch_size: 64
  num_epochs: 20
  learning_rate: 0.001
  clip_grad: 1.0
  teacher_forcing_ratio: 0.5
  patience: 5
  save_dir: "checkpoints"

inference:
  beam_size: 5
  max_length: 100
  min_length: 5 